services:
  max-app:
    container_name: max-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor
    ports:
      - "8000:8000"
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - max-mysql
    networks:
      - max-network

  max-mysql:
    container_name: max-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: client_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - max-network
  max-node:
    container_name: max-node
    image: node:20
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - max-app
    networks:
      - max-network
volumes:
  mysql_data:

networks:
  max-network:
    driver: bridge